#SVM

Iris dataset

# Linear

In [18]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC

In [19]:
data = pd.read_csv(r"/content/Iris Data.csv")
X = data.iloc[:,:-1]
y = data.iloc[:,-1]

In [20]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.5)

In [21]:
svc = SVC(kernel = 'linear')
svc.fit(X_train,y_train)

SVC(kernel='linear')

In [22]:
y_pred = svc.predict(X_test)

In [23]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [24]:
print(confusion_matrix(y_test,y_pred))

[[5 0 0]
 [0 6 0]
 [0 0 5]]


In [25]:
print(accuracy_score(y_test,y_pred))

1.0


In [26]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

      Setosa       1.00      1.00      1.00         5
  Versicolor       1.00      1.00      1.00         6
   Virginica       1.00      1.00      1.00         5

    accuracy                           1.00        16
   macro avg       1.00      1.00      1.00        16
weighted avg       1.00      1.00      1.00        16



# Poly

In [12]:
svc_poly = SVC(kernel = 'poly')
svc_poly.fit(X_train,y_train)

SVC(kernel='poly')

In [33]:
y_pred_poly = svc_poly.predict(X_test)

In [34]:
print(confusion_matrix(y_test,y_pred_poly))

[[5 0 0]
 [0 6 0]
 [0 0 5]]


In [35]:
print(accuracy_score(y_test,y_pred))

1.0


In [36]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

      Setosa       1.00      1.00      1.00         5
  Versicolor       1.00      1.00      1.00         6
   Virginica       1.00      1.00      1.00         5

    accuracy                           1.00        16
   macro avg       1.00      1.00      1.00        16
weighted avg       1.00      1.00      1.00        16



#RBF

In [27]:
svc_rbf = SVC(kernel = 'rbf')
svc_rbf.fit(X_train,y_train)

SVC()

In [37]:
y_pred_rbf = svc_rbf.predict(X_test)

In [38]:
print(confusion_matrix(y_test,y_pred_rbf))

[[5 0 0]
 [0 1 5]
 [0 0 5]]


In [39]:
print(accuracy_score(y_test,y_pred_rbf))

0.6875


In [40]:
print(classification_report(y_test,y_pred_rbf))

              precision    recall  f1-score   support

      Setosa       1.00      1.00      1.00         5
  Versicolor       1.00      0.17      0.29         6
   Virginica       0.50      1.00      0.67         5

    accuracy                           0.69        16
   macro avg       0.83      0.72      0.65        16
weighted avg       0.84      0.69      0.63        16

